language: node_js
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - "4.2"
  - "5.1"
before_script:
  - npm prune
script:
  - npm run eslint
  - npm run coverage
  - npm run build
after_success:
  - npm run report-coverage