language: node_js
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - "6"
env:
  global:
    - DETAILED=false
  matrix:
    - DETAILED=true
matrix:
  include:
    - node_js: "4"
      env:
    - node_js: "5"
      env:
    - node_js: "7"
      env:
before_script:
  - npm prune
script:
  - npm run eslint
  - npm run coverage
  - npm run build
  - "[ $DETAILED == false ] || npm run test-sl"
after_success:
  - "[ $DETAILED == false ] || npm run report-coverage"